define([], function () {

    var ddlItem = function (value, name) {
        this.itemValue = value;
        this.itemName = name;
    },
    PROVINCEDDL = ko.observableArray([
                new ddlItem("0", "Lower Coastal Plain"),
                new ddlItem("1", "Middle Coastal Plain"),
                new ddlItem("2", "Upper Coastal Plain"),
                new ddlItem("3", "Piedmont"),
                new ddlItem("4", "Blue Ridge Mountains"),
    ]),
    COUNTIESDDL = ko.observableArray(['ABBEVILLE', 'AIKEN', 'ALLENDALE', 'ANDERSON', 'BAMBERG', 'BARNWELL', 'BEAUFORT', 'BERKELEY',
        'CALHOUN', 'CHARLESTON', 'CHEROKEE', 'CHESTER', 'CHESTERFIELD', 'CLARENDON', 'COLLETON', 'DARLINGTON', 'DILLON',
        'DORCHESTER', 'EDGEFIELD', 'FAIRFIELD', 'FLORENCE', 'GEORGETOWN', 'GREENVILLE', 'GREENWOOD', 'HAMPTON', 'HORRY', 'JASPER',
    'KERSHAW', 'LANCASTER', 'LAURENS', 'LEE', 'LEXINGTON', 'MARION', 'MARLBORO', 'MCCORMICK', 'NEWBERRY', 'OCONEE', 'ORANGEBURG',
    'PICKENS', 'RICHLAND', 'SALUDA', 'SPARTANBURG', 'SUMTER', 'UNION', 'WILLIAMSBURG', 'YORK']),
    SITEID = ko.observable(),
    STATE = ko.observable(),
    COUNTY = ko.observable(),
    SITENUMBER = ko.observable(),
    RECORDEDBY = ko.observable(),
    AFFILIATION = ko.observable(),
    RECORDEDDATE = ko.observable(),
    SITENAME = ko.observable(),
    PROJECT = ko.observable(),
    USGSQUADRANGLE = ko.observable(),
    UTMZONE = ko.observable(),
    EASTING = ko.observable(),
    NORTHING = ko.observable(),
    GPSEASTING = ko.observable(),
    GPSNORTHING = ko.observable(),
    GPSUNITDESC = ko.observable(),
    AI_SURVEY = ko.observable(),
    AI_TESTING = ko.observable(),
    AI_EXCAVATION = ko.observable(),
    PROPERTYOWNER = ko.observable(),
    PHONENUMBER = ko.observable(),
    ADDRESS = ko.observable(),
    NRHP_ELIGIBLE = ko.observable(),
    NRHP_NONELIGIBLE = ko.observable(),
    NRHP_ADDWORK = ko.observable(),
    LOS_NATIONAL = ko.observable(),
    LOS_STATE = ko.observable(),
    LOS_LOCAL = ko.observable(),
    PROVINCE = ko.observable(),
    LANDFORMLOCATION = ko.observable(),
    SITEELEVATION = ko.observable(),
    SOILTYPE = ko.observable(),
    SOILCLASSIFICATION = ko.observable(),
    MAJORRIVER = ko.observable(),
    NEARESTRIVERSTREAM = ko.observable(),
    CV_PINECONF = ko.observable(),
    CV_HARDWOOD = ko.observable(),
    CV_MIXEDPINEHW = ko.observable(),
    CV_OLDFIELD = ko.observable(),
    CV_GRASSPASTURE = ko.observable(),
    CV_AGRICULTURE = ko.observable(),
    CV_WETLANDSFRESHWAT = ko.observable(),
    CV_WETLANDSSALTWAT = ko.observable(),
    CV_OTHER = ko.observable(),
    COVERTYPE = ko.observable(),
    SITELENGTH = ko.observable(),
    SITEWIDTH = ko.observable(),
    SITEDEPTH = ko.observable(),
    NH_MIDDEN = ko.observable(),
    NH_FLORAL = ko.observable(),
    NH_FAUNA = ko.observable(),
    NH_SHELL = ko.observable(),
    NH_CHARCOAL = ko.observable(),
    HUMANREMAINS = ko.observable(),
    HUMANREMAINSPRESERVATION = ko.observable(),
    MAPSCALE = ko.observable(),
    ARC_PALEO = ko.observable(),
    ARC_EARLYARCHAIC = ko.observable(),
    ARC_MIDDLEARCHAIC = ko.observable(),
    ARC_LATEARCHAIC = ko.observable(),
    ARC_ANYARCHAIC = ko.observable(),
    ARC_EARLYWOODLAND = ko.observable(),
    ARC_MIDDLEWOODLAND = ko.observable(),
    ARC_LATEWOODLAND = ko.observable(),
    ARC_ANYWOODLAND = ko.observable(),
    ARC_MISSISSIPPIAN = ko.observable(),
    ARC_LATEPREHISTORIC = ko.observable(),
    ARC_UNKNOWNPREHISTORIC = ko.observable(),
    ARC_ERAPREHISTORIC = ko.observable(),
    ARC_16CENTURY = ko.observable(),
    ARC_17CENTURY = ko.observable(),
    ARC_18CENTURY = ko.observable(),
    ARC_19CENTURY = ko.observable(),
    ARC_20CENTURY = ko.observable(),
    ARC_UNKNOWNHISTORIC = ko.observable(),
    TOTALARTIFACTS = ko.observable(),
    VIS_0 = ko.observable(),
    VIS_1_25 = ko.observable(),
    VIS_26_50 = ko.observable(),
    VIS_51_75 = ko.observable(),
    VIS_76_100 = ko.observable(),
    TOTALHOURSCOLLECTING = ko.observable(),
    CT_GRID = ko.observable(),
    CT_CONTROLLED = ko.observable(),
    CT_GRAB = ko.observable(),
    CT_OTHER = ko.observable(),
    COLEXT_COMPLETE = ko.observable(),
    COLEXT_SELECTIVE = ko.observable(),
    COLEXT_NO_COLLECT = ko.observable(),
    TESTINGMETHOD = ko.observable(),
    LU_AGRICULTURE = ko.observable(),
    LU_FOREST = ko.observable(),
    LU_FALLOW = ko.observable(),
    LU_RESIDENTIALLD = ko.observable(),
    LU_RESIDENTIALHD = ko.observable(),
    LU_COMMERCIAL = ko.observable(),
    LU_INDUSTRIAL = ko.observable(),
    LU_OTHER = ko.observable(),
    SITEINTEGRITY = ko.observable(),
    DAMAGEEXTENT = ko.observable(),
    DAMAGE_EROSION = ko.observable(),
    DAMAGE_CULTIVATION = ko.observable(),
    DAMAGE_LOGGING = ko.observable(),
    DAMAGE_CONSTRUCTION = ko.observable(),
    DAMAGE_VANDALISM = ko.observable(),
    DAMAGE_INUNDATION = ko.observable(),
    DAMAGE_OTHER = ko.observable(),
    THREATPOTENTIAL = ko.observable(),
    THREAT_EROSION = ko.observable(),
    THREAT_CULTIVATION = ko.observable(),
    THREAT_LOGGING = ko.observable(),
    THREAT_CONSTRUCTION = ko.observable(),
    THREAT_VANDALISM = ko.observable(),
    THREAT_INUNDATION = ko.observable(),
    THREAT_OTHER = ko.observable(),
    REC_SURVEY = ko.observable(),
    REC_TESTING = ko.observable(),
    REC_EXCAVATION = ko.observable(),
    REC_ARCHIVAL = ko.observable(),
    REC_NONE = ko.observable(),
    REC_OTHER = ko.observable(),
    IMPACTZONE = ko.observable(),
    ARCHIVE = ko.observable(),
    GROUPID = ko.observable(),
    HISTORICALARCHIVALDOC = ko.observable(),
    ARCHAEOLOGICALDOC = ko.observable(),
    COLLECTIONSLOCATION = ko.observable(),
    PHOTOLOCATION = ko.observable(),
    SAMPLELOCATION = ko.observable(),
    SAMPLETYPE = ko.observable(),
    DST_PREHISTORIC = ko.observable(),
    DST_HISTORIC = ko.observable(),
    OTHERMAPREFNOTES = ko.observable(),
    OTHERSITEDESIGNATIONS = ko.observable(),
    JUSTIFICATION = ko.observable(),
    VEGCOMMENTS = ko.observable(),
    CULTURALFEATURES = ko.observable(),
    GENERALSITEDESCRIPTION = ko.observable(),
    LOCATIONDESCRIPTION = ko.observable(),
    COLLECTIONCOMMENTS = ko.observable(),
    EXCAVATIONCOMMENTS = ko.observable(),
    LANDUSECOMMENTS = ko.observable(),
    DAMAGECOMMENTS = ko.observable(),
    THREATCOMMENTS = ko.observable(),
    RECOMMENDCOMMENTS = ko.observable(),
    HISTORICALARCHIVALDOCNOTES = ko.observable(),
    ARCHAEOLOGICALDOCNOTES = ko.observable(),
    MANAGEMENTCOMMENTS = ko.observable(),
    SITEENTEREDINDBDATE = ko.observable(),
    DETERMINATION = ko.observable(),
    DATEDETERMINED = ko.observable(),
    ONNRHP = ko.observable(),
    NRHPDATE = ko.observable(),
    REVISIT = ko.observable(),
    REVISITNUM = ko.observable(),
    RECORD_OWNER = ko.observable(),
    EDIT_DATE_FROM = ko.observable(),
    EDIT_DATE_TO = ko.observable(),
    GEO_VALID = ko.observable(),
    STATUS = ko.observable();

    return {
        PROVINCEDDL: PROVINCEDDL,
        COUNTIESDDL: COUNTIESDDL,
        SITEID: SITEID,
        STATE: STATE,
        COUNTY: COUNTY,
        SITENUMBER: SITENUMBER,
        RECORDEDBY: RECORDEDBY,
        AFFILIATION: AFFILIATION,
        RECORDEDDATE: RECORDEDDATE,
        SITENAME: SITENAME,
        PROJECT: PROJECT,
        USGSQUADRANGLE: USGSQUADRANGLE,
        UTMZONE: UTMZONE,
        EASTING: EASTING,
        NORTHING: NORTHING,
        GPSEASTING: GPSEASTING,
        GPSNORTHING: GPSNORTHING,
        GPSUNITDESC: GPSUNITDESC,
        AI_SURVEY: AI_SURVEY,
        AI_TESTING: AI_TESTING,
        AI_EXCAVATION: AI_EXCAVATION,
        PROPERTYOWNER: PROPERTYOWNER,
        PHONENUMBER: PHONENUMBER,
        ADDRESS: ADDRESS,
        NRHP_ELIGIBLE: NRHP_ELIGIBLE,
        NRHP_NONELIGIBLE: NRHP_NONELIGIBLE,
        NRHP_ADDWORK: NRHP_ADDWORK,
        LOS_NATIONAL: LOS_NATIONAL,
        LOS_STATE: LOS_STATE,
        LOS_LOCAL: LOS_LOCAL,
        PROVINCE: PROVINCE,
        LANDFORMLOCATION: LANDFORMLOCATION,
        SITEELEVATION: SITEELEVATION,
        SOILTYPE: SOILTYPE,
        SOILCLASSIFICATION: SOILCLASSIFICATION,
        MAJORRIVER: MAJORRIVER,
        NEARESTRIVERSTREAM: NEARESTRIVERSTREAM,
        CV_PINECONF: CV_PINECONF,
        CV_HARDWOOD: CV_HARDWOOD,
        CV_MIXEDPINEHW: CV_MIXEDPINEHW,
        CV_OLDFIELD: CV_OLDFIELD,
        CV_GRASSPASTURE: CV_GRASSPASTURE,
        CV_AGRICULTURE: CV_AGRICULTURE,
        CV_WETLANDSFRESHWAT: CV_WETLANDSFRESHWAT,
        CV_WETLANDSSALTWAT: CV_WETLANDSSALTWAT,
        CV_OTHER: CV_OTHER,
        COVERTYPE: COVERTYPE,
        SITELENGTH: SITELENGTH,
        SITEWIDTH: SITEWIDTH,
        SITEDEPTH: SITEDEPTH,
        NH_MIDDEN: NH_MIDDEN,
        NH_FLORAL: NH_FLORAL,
        NH_FAUNA: NH_FAUNA,
        NH_SHELL: NH_SHELL,
        NH_CHARCOAL: NH_CHARCOAL,
        HUMANREMAINS: HUMANREMAINS,
        HUMANREMAINSPRESERVATION: HUMANREMAINSPRESERVATION,
        MAPSCALE: MAPSCALE,
        ARC_PALEO: ARC_PALEO,
        ARC_EARLYARCHAIC: ARC_EARLYARCHAIC,
        ARC_MIDDLEARCHAIC: ARC_MIDDLEARCHAIC,
        ARC_LATEARCHAIC: ARC_LATEARCHAIC,
        ARC_ANYARCHAIC: ARC_ANYARCHAIC,
        ARC_EARLYWOODLAND: ARC_EARLYWOODLAND,
        ARC_MIDDLEWOODLAND: ARC_MIDDLEWOODLAND,
        ARC_LATEWOODLAND: ARC_LATEWOODLAND,
        ARC_ANYWOODLAND: ARC_ANYWOODLAND,
        ARC_MISSISSIPPIAN: ARC_MISSISSIPPIAN,
        ARC_LATEPREHISTORIC: ARC_LATEPREHISTORIC,
        ARC_UNKNOWNPREHISTORIC: ARC_UNKNOWNPREHISTORIC,
        ARC_ERAPREHISTORIC: ARC_ERAPREHISTORIC,
        ARC_16CENTURY: ARC_16CENTURY,
        ARC_17CENTURY: ARC_17CENTURY,
        ARC_18CENTURY: ARC_18CENTURY,
        ARC_19CENTURY: ARC_19CENTURY,
        ARC_20CENTURY: ARC_20CENTURY,
        ARC_UNKNOWNHISTORIC: ARC_UNKNOWNHISTORIC,
        TOTALARTIFACTS: TOTALARTIFACTS,
        VIS_0: VIS_0,
        VIS_1_25: VIS_1_25,
        VIS_26_50: VIS_26_50,
        VIS_51_75: VIS_51_75,
        VIS_76_100: VIS_76_100,
        TOTALHOURSCOLLECTING: TOTALHOURSCOLLECTING,
        CT_GRID: CT_GRID,
        CT_CONTROLLED: CT_CONTROLLED,
        CT_GRAB: CT_GRAB,
        CT_OTHER: CT_OTHER,
        COLEXT_COMPLETE: COLEXT_COMPLETE,
        COLEXT_SELECTIVE: COLEXT_SELECTIVE,
        COLEXT_NO_COLLECT: COLEXT_NO_COLLECT,
        TESTINGMETHOD: TESTINGMETHOD,
        LU_AGRICULTURE: LU_AGRICULTURE,
        LU_FOREST: LU_FOREST,
        LU_FALLOW: LU_FALLOW,
        LU_RESIDENTIALLD: LU_RESIDENTIALLD,
        LU_RESIDENTIALHD: LU_RESIDENTIALHD,
        LU_COMMERCIAL: LU_COMMERCIAL,
        LU_INDUSTRIAL: LU_INDUSTRIAL,
        LU_OTHER: LU_OTHER,
        SITEINTEGRITY: SITEINTEGRITY,
        DAMAGEEXTENT: DAMAGEEXTENT,
        DAMAGE_EROSION: DAMAGE_EROSION,
        DAMAGE_CULTIVATION: DAMAGE_CULTIVATION,
        DAMAGE_LOGGING: DAMAGE_LOGGING,
        DAMAGE_CONSTRUCTION: DAMAGE_CONSTRUCTION,
        DAMAGE_VANDALISM: DAMAGE_VANDALISM,
        DAMAGE_INUNDATION: DAMAGE_INUNDATION,
        DAMAGE_OTHER: DAMAGE_OTHER,
        THREATPOTENTIAL: THREATPOTENTIAL,
        THREAT_EROSION: THREAT_EROSION,
        THREAT_CULTIVATION: THREAT_CULTIVATION,
        THREAT_LOGGING: THREAT_LOGGING,
        THREAT_CONSTRUCTION: THREAT_CONSTRUCTION,
        THREAT_VANDALISM: THREAT_VANDALISM,
        THREAT_INUNDATION: THREAT_INUNDATION,
        THREAT_OTHER: THREAT_OTHER,
        REC_SURVEY: REC_SURVEY,
        REC_TESTING: REC_TESTING,
        REC_EXCAVATION: REC_EXCAVATION,
        REC_ARCHIVAL: REC_ARCHIVAL,
        REC_NONE: REC_NONE,
        REC_OTHER: REC_OTHER,
        IMPACTZONE: IMPACTZONE,
        ARCHIVE: ARCHIVE,
        GROUPID: GROUPID,
        HISTORICALARCHIVALDOC: HISTORICALARCHIVALDOC,
        ARCHAEOLOGICALDOC: ARCHAEOLOGICALDOC,
        COLLECTIONSLOCATION: COLLECTIONSLOCATION,
        PHOTOLOCATION: PHOTOLOCATION,
        SAMPLELOCATION: SAMPLELOCATION,
        SAMPLETYPE: SAMPLETYPE,
        DST_PREHISTORIC: DST_PREHISTORIC,
        DST_HISTORIC: DST_HISTORIC,
        OTHERMAPREFNOTES: OTHERMAPREFNOTES,
        OTHERSITEDESIGNATIONS: OTHERSITEDESIGNATIONS,
        JUSTIFICATION: JUSTIFICATION,
        VEGCOMMENTS: VEGCOMMENTS,
        CULTURALFEATURES: CULTURALFEATURES,
        GENERALSITEDESCRIPTION: GENERALSITEDESCRIPTION,
        LOCATIONDESCRIPTION: LOCATIONDESCRIPTION,
        COLLECTIONCOMMENTS: COLLECTIONCOMMENTS,
        EXCAVATIONCOMMENTS: EXCAVATIONCOMMENTS,
        LANDUSECOMMENTS: LANDUSECOMMENTS,
        DAMAGECOMMENTS: DAMAGECOMMENTS,
        THREATCOMMENTS: THREATCOMMENTS,
        RECOMMENDCOMMENTS: RECOMMENDCOMMENTS,
        HISTORICALARCHIVALDOCNOTES: HISTORICALARCHIVALDOCNOTES,
        ARCHAEOLOGICALDOCNOTES: ARCHAEOLOGICALDOCNOTES,
        MANAGEMENTCOMMENTS: MANAGEMENTCOMMENTS,
        SITEENTEREDINDBDATE: SITEENTEREDINDBDATE,
        DETERMINATION: DETERMINATION,
        DATEDETERMINED: DATEDETERMINED,
        ONNRHP: ONNRHP,
        NRHPDATE: NRHPDATE,
        REVISIT: REVISIT,
        REVISITNUM: REVISITNUM,
        RECORD_OWNER: RECORD_OWNER,
        EDIT_DATE_FROM: EDIT_DATE_FROM,
        EDIT_DATE_TO: EDIT_DATE_TO,
        GEO_VALID: GEO_VALID,
        STATUS: STATUS
    }

});